# Generated by Django 3.1.5 on 2021-01-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelchangAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='익명', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='none', max_length=6)),
                ('age', models.IntegerField(null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('q1', models.IntegerField(default=0)),
                ('q2', models.IntegerField(default=0)),
                ('q3', models.IntegerField(default=0)),
                ('q4', models.IntegerField(default=0)),
                ('q5', models.IntegerField(default=0)),
                ('q6', models.IntegerField(default=0)),
                ('q7', models.IntegerField(default=0)),
                ('q8', models.IntegerField(default=0)),
                ('q9', models.IntegerField(default=0)),
                ('q10', models.IntegerField(default=0)),
                ('q11', models.IntegerField(default=0)),
                ('q12', models.IntegerField(default=0)),
                ('q13', models.IntegerField(default=0)),
                ('q14', models.IntegerField(default=0)),
                ('q15', models.IntegerField(default=0)),
                ('q16', models.IntegerField(default=0)),
                ('q17', models.IntegerField(default=0)),
                ('q18', models.IntegerField(default=0)),
                ('q19', models.IntegerField(default=0)),
                ('q20', models.IntegerField(default=0)),
                ('result', models.CharField(default='none', max_length=20)),
            ],
        ),
    ]
