# Generated by Django 3.1.5 on 2021-01-15 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbti',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 16, 21, 96179)),
        ),
        migrations.AddField(
            model_name='hbti',
            name='user',
            field=models.CharField(default='익명', max_length=20),
        ),
    ]
