# Generated by Django 3.1.5 on 2021-01-15 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0002_auto_20210115_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbti',
            name='result',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hbti',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 14, 29, 49, 568002)),
        ),
    ]
