# Generated by Django 3.1.5 on 2021-01-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0003_auto_20210115_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbti',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
