# Generated by Django 3.1.5 on 2021-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0005_auto_20210115_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbti',
            name='result',
            field=models.CharField(default='none', max_length=4),
        ),
    ]
