# Generated by Django 3.1.5 on 2021-01-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0011_auto_20210115_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbti',
            name='q1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q10',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q11',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q12',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q13',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q14',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q15',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q16',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q17',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q18',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q19',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q20',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q9',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
