# Generated by Django 3.1.5 on 2021-01-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0012_auto_20210115_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hbti',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q20',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='hbti',
            name='q9',
        ),
    ]
