# Generated by Django 3.1.5 on 2021-01-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbties', '0013_auto_20210115_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbti',
            name='q1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q10',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q11',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q12',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q13',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q14',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q15',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q16',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q17',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q18',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q19',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q20',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q6',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q7',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q8',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='hbti',
            name='q9',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='hbti',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='none', max_length=6),
        ),
        migrations.AlterField(
            model_name='hbti',
            name='result',
            field=models.CharField(choices=[('INFP', 'INFP'), ('ESTJ', 'ESTJ'), ('ESTP', 'ESTP'), ('ESFJ', 'ESFJ'), ('ESFP', 'ESFP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISTP', 'ISTP'), ('ISFJ', 'ISFJ'), ('ISFP', 'ISFP'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('INFJ', 'INFJ')], default='none', max_length=4),
        ),
    ]
